name: "Deploy"
on: workflow_dispatch
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ACCOUNT_NAME: "production"
  ENVIRONMENT_NAME: "prod"
  ACCOUNT_NUMBER: "288150501556"
  SHARED_SERVICES_ACCOUNT_NUMBER: "368836370510"
  APP_NAME: "live-iq"
  REGION: "eu-west-2"
  AMPLIFY_APP_ID: "d3hxb1jagprfvi"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.REGION}}
          role-to-assume: "arn:aws:iam::${{env.ACCOUNT_NUMBER}}:role/${{env.APP_NAME}}-deployment-role"
          role-duration-seconds: 1200

      - id: start-job
        run: |
          JOB_OUTPUT=$(aws amplify start-job --app-id ${{env.AMPLIFY_APP_ID}} --branch-name main --job-type RELEASE)
          echo "::set-output name=jobId::$(echo $JOB_OUTPUT | jq -r .jobSummary.jobId)"
      - run: |
          sleep 2s
          JOB_ID=${{ steps.start-job.outputs.jobId }}
          while true; do
            OUTPUT=$(aws amplify get-job --app-id ${{env.AMPLIFY_APP_ID}} --branch-name main --job-id $JOB_ID)
            STATUS=$(echo $OUTPUT | jq -r .job.summary.status)
            echo "Status: $STATUS"
            if [ "$STATUS" == "FAILED" ] || [ "$STATUS" == "CANCELLED" ]; then exit 1; fi
            if [ "$STATUS" == "SUCCEED" ]; then break; fi
            sleep 2s
          done
