name: 'Merge dev to demoo'

on: workflow_dispatch

jobs:
  dev-test-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      # Although this is called nightly merge, this actually just merges dev into demo.
      # The trigger for this is the on expression we have above which will trigger this
      # when the workflow is manually triggered
      - name: Dev Demo Merge
        uses: robotology/gh-action-nightly-merge@v1.3.1
        with:
          stable_branch: 'dev'
          development_branch: 'demo'
          allow_ff: true
          ff_only: true
          allow_forks: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
