name: "Prepare the next release"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag"

jobs:
  prepareRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev
        uses: actions/checkout@v1

      - name: Setup Git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      # This step writes the CHANGELOG from the files in the
      # CHANGELOG folder, removes the files, commits the changes
      # and tags the latest commit using the tag provided when
      # executing the action
      - name: Prepare release
        run: ./prepareRelease.sh ${{ github.event.inputs.tag }}

      - name: Push changes to dev
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push tags
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true

      # Although this is called nightly merge, this actually just merges dev into main.
      # The trigger for this is the on expression we have above which will trigger this
      # step and those above when we manually trigger the action.
      - name: Dev Main Merge
        uses: robotology/gh-action-nightly-merge@v1.3.1
        with:
          stable_branch: "dev"
          development_branch: "main"
          allow_ff: true
          ff_only: true
          allow_forks: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
