name: run-tests
on:  workflow_dispatch
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: '14.x'
          registry-url: https://npm.pkg.github.com
          scope: '@statsbomb'
      - run: |
          exit 1
