name: run-tests
on: pull_request
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: '14.x'
          registry-url: https://npm.pkg.github.com
          scope: '@statsbomb'
      - run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
      - run: cd packages/iqlive-react-components && yarn build:messages # Need to compile the messages before running Eslint
      - run: cd ./ && yarn test:ci
